name: Build & Deploy
on:
    push:
        branches: [main]
        
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy app
              uses: appleboy/ssh-action@master
              with:
                host: ${{secrets.SSH_HOST}}
                key: ${{secrets.SSH_KEY}}
                username: ${{secrets.SSH_USERNAME}}
                
                script: |
                    export PATH=$PATH:/root/.nvm/versions/node/v17.6.0/bin
                    cd ~/int-bot-v2
                    pm2 stop int-server bot
                    git pull
                    npm install
                    pm2 reload int-server bot
